import {
  Card,
  CardContent,
  Typography,
  Chip,
  Box,
  IconButton,
  Tooltip,
  Divider,
  Stack,
} from '@mui/material';
import {
  CheckCircle as CheckCircleIcon,
  Cancel as CancelIcon,
  Edit as EditIcon,
  EventAvailable as EventAvailableIcon,
  AutoAwesome as AutoAwesomeIcon,
} from '@mui/icons-material';
import {
  StatusAgendamento,
  StatusAgendamentoLabels,
  StatusAgendamentoColors,
  TipoAtendimentoLabels,
  PrioridadeLabels,
} from '../../api/agendamentoPaciente.dto';
import type { AgendamentoPacienteResponse } from '../../api/agendamentoPaciente.dto';
import type { AgendamentoAcompanhanteResponse } from '../../api/agendamentoAcompanhante.dto';

type AppointmentData = AgendamentoPacienteResponse | AgendamentoAcompanhanteResponse;

interface AppointmentCardProps {
  appointment: AppointmentData;
  type: 'patient' | 'companion';
  onConfirm?: (uuid: string, confirmedBy: 'patient' | 'professional') => void;
  onCancel?: (uuid: string) => void;
  onEdit?: (uuid: string) => void;
}

export default function AppointmentCard({
  appointment,
  type,
  onConfirm,
  onCancel,
  onEdit,
}: AppointmentCardProps) {
  const isPatient = type === 'patient';
  const patientName = isPatient
    ? (appointment as AgendamentoPacienteResponse).pacienteNome
    : (appointment as AgendamentoAcompanhanteResponse).acompanhanteNome;

  const confirmadoPessoa = isPatient
    ? (appointment as AgendamentoPacienteResponse).confirmadoPaciente
    : (appointment as AgendamentoAcompanhanteResponse).confirmadoAcompanhante;

  // Check if geradoAutomaticamente exists (only patient appointments have this field)
  const isAutoGenerated = 'geradoAutomaticamente' in appointment && appointment.geradoAutomaticamente;
  const motivoAutomatico = 'motivoGeracaoAutomatica' in appointment ? appointment.motivoGeracaoAutomatica : null;

  return (
    <Card
      sx={{
        mb: 2,
        border: isAutoGenerated ? '2px solid #1976d2' : undefined,
        position: 'relative',
      }}
    >
      {isAutoGenerated && (
        <Tooltip title={`Agendamento gerado automaticamente: ${motivoAutomatico || ''}`}>
          <Chip
            icon={<AutoAwesomeIcon />}
            label="Automático"
            color="primary"
            size="small"
            sx={{ position: 'absolute', top: 8, right: 8 }}
          />
        </Tooltip>
      )}

      <CardContent>
        <Stack spacing={2}>
          {/* Header */}
          <Box display="flex" justifyContent="space-between" alignItems="flex-start">
            <Box>
              <Typography variant="h6" gutterBottom>
                {patientName}
              </Typography>
              <Typography variant="body2" color="text.secondary">
                {appointment.tipoServicoNome}
              </Typography>
            </Box>
            <Chip
              label={StatusAgendamentoLabels[appointment.status as StatusAgendamento]}
              color={StatusAgendamentoColors[appointment.status as StatusAgendamento]}
              size="small"
            />
          </Box>

          <Divider />

          {/* Details */}
          <Box>
            <Typography variant="body2" color="text.secondary">
              <strong>Profissional:</strong> {appointment.profissionalNome}
            </Typography>
            <Typography variant="body2" color="text.secondary">
              <strong>Data/Hora:</strong>{' '}
              {new Date(appointment.dataHoraInicio).toLocaleString('pt-BR')} -{' '}
              {new Date(appointment.dataHoraFim).toLocaleTimeString('pt-BR')}
            </Typography>
            {appointment.tipoAtendimento && (
              <Typography variant="body2" color="text.secondary">
                <strong>Tipo:</strong> {TipoAtendimentoLabels[appointment.tipoAtendimento as keyof typeof TipoAtendimentoLabels]}
              </Typography>
            )}
            {appointment.prioridade && (
              <Typography variant="body2" color="text.secondary">
                <strong>Prioridade:</strong> {PrioridadeLabels[appointment.prioridade as keyof typeof PrioridadeLabels]}
              </Typography>
            )}
            {appointment.observacoes && (
              <Typography variant="body2" color="text.secondary" sx={{ mt: 1 }}>
                <strong>Observações:</strong> {appointment.observacoes}
              </Typography>
            )}
            {appointment.motivoCancelamento && (
              <Typography variant="body2" color="error" sx={{ mt: 1 }}>
                <strong>Motivo do Cancelamento:</strong> {appointment.motivoCancelamento}
              </Typography>
            )}
          </Box>

          {/* Confirmation Status */}
          <Box display="flex" gap={2} alignItems="center">
            <Tooltip title={confirmadoPessoa ? 'Confirmado pelo paciente/acompanhante' : 'Aguardando confirmação'}>
              <Chip
                icon={confirmadoPessoa ? <CheckCircleIcon /> : <EventAvailableIcon />}
                label={isPatient ? 'Paciente' : 'Acompanhante'}
                color={confirmadoPessoa ? 'success' : 'default'}
                size="small"
              />
            </Tooltip>
            <Tooltip title={appointment.confirmadoProfissional ? 'Confirmado pelo profissional' : 'Aguardando confirmação'}>
              <Chip
                icon={appointment.confirmadoProfissional ? <CheckCircleIcon /> : <EventAvailableIcon />}
                label="Profissional"
                color={appointment.confirmadoProfissional ? 'success' : 'default'}
                size="small"
              />
            </Tooltip>
          </Box>

          {/* Actions */}
          {appointment.status !== StatusAgendamento.CANCELADO &&
            appointment.status !== StatusAgendamento.CONCLUIDO && (
              <Box display="flex" justifyContent="flex-end" gap={1}>
                {!confirmadoPessoa && onConfirm && (
                  <Tooltip title={`Confirmar como ${isPatient ? 'paciente' : 'acompanhante'}`}>
                    <IconButton
                      size="small"
                      color="success"
                      onClick={() => onConfirm(appointment.uuid, 'patient')}
                    >
                      <CheckCircleIcon />
                    </IconButton>
                  </Tooltip>
                )}
                {!appointment.confirmadoProfissional && onConfirm && (
                  <Tooltip title="Confirmar como profissional">
                    <IconButton
                      size="small"
                      color="primary"
                      onClick={() => onConfirm(appointment.uuid, 'professional')}
                    >
                      <CheckCircleIcon />
                    </IconButton>
                  </Tooltip>
                )}
                {onEdit && (
                  <Tooltip title="Editar">
                    <IconButton size="small" color="info" onClick={() => onEdit(appointment.uuid)}>
                      <EditIcon />
                    </IconButton>
                  </Tooltip>
                )}
                {onCancel && (
                  <Tooltip title="Cancelar">
                    <IconButton
                      size="small"
                      color="error"
                      onClick={() => onCancel(appointment.uuid)}
                    >
                      <CancelIcon />
                    </IconButton>
                  </Tooltip>
                )}
              </Box>
            )}
        </Stack>
      </CardContent>
    </Card>
  );
}
